[project]
name = "browser-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "llama-index-llms-google-genai>=0.2.1",
    "pyperclip>=1.9.0",
    "toga-winforms>=0.5.1",
]
